{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "opencommerce.name" . }}
    component: web
    chart: {{ template "opencommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "opencommerce.fullname" . }}-web
  namespace: {{ .Release.Namespace | quote }} 
spec:
  selector:
    matchLabels:
      app: {{ template "opencommerce.name" . }}
      component: web
      release: {{ .Release.Name }}
  replicas: {{ .Values.web.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "opencommerce.name" . }}
        component: web
        release: {{ .Release.Name }}
    spec:
      containers:
        {{- if .Values.web.image.imagePullSecret }}
        imagePullSecrets:
          - name: {{ .Values.web.image.imagePullSecret }}
        {{- end }}
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 4000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ template "opencommerce.fullname" . }}
            - configMapRef:
                name: {{ template "opencommerce.fullname" . }}-web
{{- end }}
